# Generated by Django 3.0.2 on 2020-02-21 14:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
