# Generated by Django 3.0.2 on 2020-02-21 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_remove_thread_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='userUpvoted',
            new_name='userUpVoted',
        ),
    ]
